#!/usr/bin/env tsx
// Reads all .m files from stdlib/ and generates src/numbl-core/stdlib-bundle.ts
//
// - stdlib/*.m        → stdlibFiles (flat, no search path needed)
// - stdlib/shims/**   → shimFiles   (preserves relative paths, needs search path)

import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative, resolve } from "path";

const ROOT = resolve(import.meta.dirname, "..");
const STDLIB_DIR = join(ROOT, "src/stdlib");
const SHIMS_DIR = join(STDLIB_DIR, "shims");
const OUT_FILE = join(ROOT, "src/numbl-core/stdlib-bundle.ts");

// Collect flat stdlib .m files
const stdlibEntries = readdirSync(STDLIB_DIR)
  .filter(f => f.endsWith(".m"))
  .sort()
  .map(name => ({
    name,
    source: readFileSync(join(STDLIB_DIR, name), "utf-8"),
  }));

// Recursively collect shim .m files (following @, +, and private dirs like the CLI scanner)
interface FileEntry {
  name: string;
  source: string;
}

function scanMFiles(dir: string, baseDir: string): FileEntry[] {
  const results: FileEntry[] = [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return results;
  }
  entries.sort();
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (
        entry.startsWith("@") ||
        entry.startsWith("+") ||
        entry === "private"
      ) {
        results.push(...scanMFiles(fullPath, baseDir));
      }
    } else if (stat.isFile() && entry.endsWith(".m")) {
      const relPath = relative(baseDir, fullPath);
      results.push({
        name: relPath,
        source: readFileSync(fullPath, "utf-8"),
      });
    }
  }
  return results;
}

const shimEntries = scanMFiles(SHIMS_DIR, SHIMS_DIR);

// Generate output
function emitArray(varName: string, entries: FileEntry[]): string[] {
  const lines: string[] = [];
  lines.push(`export const ${varName}: WorkspaceFile[] = [`);
  for (const { name, source } of entries) {
    lines.push("  {");
    lines.push(`    name: ${JSON.stringify(name)},`);
    lines.push(`    source: ${JSON.stringify(source)},`);
    lines.push("  },");
  }
  lines.push("];");
  return lines;
}

const lines = [
  "// Auto-generated by scripts/bundle-stdlib.ts — do not edit manually.",
  'import type { WorkspaceFile } from "./workspace/types.js";',
  "",
  ...emitArray("stdlibFiles", stdlibEntries),
  "",
  ...emitArray("shimFiles", shimEntries),
  "",
];

const content = lines.join("\n");

const existing = (() => {
  try {
    return readFileSync(OUT_FILE, "utf-8");
  } catch {
    return null;
  }
})();

if (existing === content) {
  console.log("stdlib-bundle.ts is up to date.");
} else {
  writeFileSync(OUT_FILE, content);
  const shimNames = shimEntries.map(e => e.name);
  console.log(
    `stdlib-bundle.ts generated: ${stdlibEntries.length} stdlib, ${shimEntries.length} shim file(s)`
  );
  if (shimNames.length > 0) {
    console.log(`  shims: ${shimNames.join(", ")}`);
  }
}
